# Generated by Django 5.1.1 on 2024-10-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emenu.vendor')),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
