# Generated by Django 5.1.1 on 2024-10-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Edibles', 'Edibles')], default='Edibles', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='emenu.vendor'),
        ),
    ]
