# Generated by Django 5.1.1 on 2024-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
