# Generated by Django 5.1.1 on 2024-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0006_alter_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Edibles', 'Edibles'), ('Others', 'Others')], default='Edibles', max_length=10),
        ),
    ]
