# Generated by Django 5.1.1 on 2024-10-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0007_alter_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='address',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
    ]
